export const ROUTES = {
  BASE: 'Base',
  MAIN: 'Main',
  HOME: 'Home',
  CHAT: 'Chat',
  GIGGZ: 'Giggz',
  WALLET: 'Wallet',
  SIGNUP: 'Signup',
  LOGIN: 'Login',
  ACCOUNT_TYPE: "AccountType",
  FORGOT_PASSWORD: 'ForgotPassword',
  SIGNUP_OFFER: 'SignupOffer',
  WELCOME: 'Welcome',
  UPLOAD_PROFILE_PIC: 'UploadProfilePic',
  VERIFICATION: 'Verification',
  VERIFY_IDENTITY: 'VerifyIdentity',
  VERIFY_PHONE: 'VerifyPhone',
  VERIFY_CODE: 'VerifyCode',
  VERIFY_HOME_ADDRESS: 'VerifyHomeAddress',
  VERIFY_KYC: 'VerifyKyc',
  NEW_PASSWORD: 'NewPassword',
  SETTINGS: 'Settings',
  NOTIFICATION_SETTINGS: 'NotificationSettings',
PASSWORD_SECURITY: 'PasswordSecurity',
};
